version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 35
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 6
  similar-code:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 100
exclude_patterns:
  - "doc/"
  - "dist/"
  - "*.json"
  - "*.lock"
  - ".codeclimate.yml"
  - ".travis.yml"
  - ".vscode/"
  - "tests/"
  - ".babelrc"
  - ".editorconfig"
  - ".gitignore"
  - ".eslintrc.json"
  - ".template.md"
  - "rollup.config.js"
  - "examples"
  - "LICENSE"
  - "README.md"
